version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: football_ttt_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: football_ttt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
