import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// ─────────────────────────────────────────────
// Reference data
// ─────────────────────────────────────────────
const LEAGUES = [
  { tag: 'premier-league', name: 'Premier League', country: 'England' },
  { tag: 'laliga', name: 'La Liga', country: 'Spain' },
  { tag: 'serie-a', name: 'Serie A', country: 'Italy' },
  { tag: 'bundesliga', name: 'Bundesliga', country: 'Germany' },
  { tag: 'ligue1', name: 'Ligue 1', country: 'France' },
  { tag: 'eredivisie', name: 'Eredivisie', country: 'Netherlands' },
  { tag: 'ligaportugal', name: 'Liga Portugal', country: 'Portugal' },
  { tag: 'superlig', name: 'Süper Lig', country: 'Turkey' },
  { tag: 'mls', name: 'MLS', country: 'USA' },
  { tag: 'saudi-league', name: 'Saudi Pro League', country: 'Saudi Arabia' },
];

const CLUBS = [
  { tag: 'barcelona', name: 'FC Barcelona', country: 'Spain', leagueTag: 'laliga' },
  { tag: 'real-madrid', name: 'Real Madrid', country: 'Spain', leagueTag: 'laliga' },
  { tag: 'atletico', name: 'Atlético Madrid', country: 'Spain', leagueTag: 'laliga' },
  { tag: 'manchester-city', name: 'Manchester City', country: 'England', leagueTag: 'premier-league' },
  { tag: 'manchester-united', name: 'Manchester United', country: 'England', leagueTag: 'premier-league' },
  { tag: 'liverpool', name: 'Liverpool FC', country: 'England', leagueTag: 'premier-league' },
  { tag: 'chelsea', name: 'Chelsea FC', country: 'England', leagueTag: 'premier-league' },
  { tag: 'arsenal', name: 'Arsenal FC', country: 'England', leagueTag: 'premier-league' },
  { tag: 'tottenham', name: 'Tottenham Hotspur', country: 'England', leagueTag: 'premier-league' },
  { tag: 'psg', name: 'Paris Saint-Germain', country: 'France', leagueTag: 'ligue1' },
  { tag: 'monaco', name: 'AS Monaco', country: 'France', leagueTag: 'ligue1' },
  { tag: 'lyon', name: 'Olympique Lyonnais', country: 'France', leagueTag: 'ligue1' },
  { tag: 'marseille', name: 'Olympique de Marseille', country: 'France', leagueTag: 'ligue1' },
  { tag: 'bavaria', name: 'Bayern München', country: 'Germany', leagueTag: 'bundesliga' },
  { tag: 'dortmund', name: 'Borussia Dortmund', country: 'Germany', leagueTag: 'bundesliga' },
  { tag: 'wolfsburg', name: 'VfL Wolfsburg', country: 'Germany', leagueTag: 'bundesliga' },
  { tag: 'juventus', name: 'Juventus FC', country: 'Italy', leagueTag: 'serie-a' },
  { tag: 'ac-milan', name: 'AC Milan', country: 'Italy', leagueTag: 'serie-a' },
  { tag: 'inter', name: 'Inter Milan', country: 'Italy', leagueTag: 'serie-a' },
  { tag: 'roma', name: 'AS Roma', country: 'Italy', leagueTag: 'serie-a' },
  { tag: 'porto', name: 'FC Porto', country: 'Portugal', leagueTag: 'ligaportugal' },
  { tag: 'benfica', name: 'SL Benfica', country: 'Portugal', leagueTag: 'ligaportugal' },
  { tag: 'ajax', name: 'AFC Ajax', country: 'Netherlands', leagueTag: 'eredivisie' },
  { tag: 'inter-miami', name: 'Inter Miami CF', country: 'USA', leagueTag: 'mls' },
  { tag: 'al-nassr', name: 'Al-Nassr FC', country: 'Saudi Arabia', leagueTag: 'saudi-league' },
  { tag: 'al-hilal', name: 'Al-Hilal SFC', country: 'Saudi Arabia', leagueTag: 'saudi-league' },
  { tag: 'sportingcp', name: 'Sporting CP', country: 'Portugal', leagueTag: 'ligaportugal' },
  { tag: 'bordeaux', name: 'Girondins de Bordeaux', country: 'France', leagueTag: 'ligue1' },
  { tag: 'psv', name: 'PSV Eindhoven', country: 'Netherlands', leagueTag: 'eredivisie' },
  { tag: 'al-ittihad', name: 'Al-Ittihad', country: 'Saudi Arabia', leagueTag: 'saudi-league' },
  { tag: 'orlandocity', name: 'Orlando City SC', country: 'USA', leagueTag: 'mls' },
  { tag: 'feyenoord', name: 'Feyenoord', country: 'Netherlands', leagueTag: 'eredivisie' },
  { tag: 'lazio', name: 'SS Lazio', country: 'Italy', leagueTag: 'serie-a' },
  { tag: 'napoli', name: 'SSC Napoli', country: 'Italy', leagueTag: 'serie-a' },
  { tag: 'lagalaxy', name: 'LA Galaxy', country: 'USA', leagueTag: 'mls' },
  { tag: 'fenerbahce', name: 'Fenerbahçe SK', country: 'Turkey', leagueTag: 'superlig' },
  { tag: 'sevilla', name: 'Sevilla FC', country: 'Spain', leagueTag: 'laliga' },
  { tag: 'lille', name: 'LOSC Lille', country: 'France', leagueTag: 'ligue1' },
  { tag: 'al-ahli', name: 'Al-Ahli', country: 'Saudi Arabia', leagueTag: 'saudi-league' },
  { tag: 'gladbach', name: 'Borussia Mönchengladbach', country: 'Germany', leagueTag: 'bundesliga' },
  { tag: 'parma', name: 'Parma Calcio', country: 'Italy', leagueTag: 'serie-a' },
  { tag: 'newcastle', name: 'Newcastle United', country: 'England', leagueTag: 'premier-league' },
  { tag: 'udinese', name: 'Udinese Calcio', country: 'Italy', leagueTag: 'serie-a' },
  { tag: 'valencia', name: 'Valencia CF', country: 'Spain', leagueTag: 'laliga' },
  { tag: 'everton', name: 'Everton FC', country: 'England', leagueTag: 'premier-league' },
  { tag: 'como', name: 'Como 1907', country: 'Italy', leagueTag: 'serie-a' },
  { tag: 'kann', name: 'Канн', country: '', leagueTag: '' },
  { tag: 'kruzeyro', name: 'Крузейро', country: '', leagueTag: '' },
  { tag: 'korintians', name: 'Коринтианс', country: '', leagueTag: '' },
  { tag: 'gremio', name: 'Гремио', country: '', leagueTag: '' },
  { tag: 'flamengo', name: 'Фламенго', country: '', leagueTag: '' },
  { tag: 'atletikumineyru', name: 'Атлетику Минейру', country: '', leagueTag: '' },
  { tag: 'keretaro', name: 'Керетаро', country: '', leagueTag: '' },
  { tag: 'fluminense', name: 'Флуминенсе', country: '', leagueTag: '' },
  { tag: 'nyu-yorkredbulls', name: 'Нью-Йорк Ред Буллс', country: '', leagueTag: '' },
  { tag: 'reyms', name: 'Реймс', country: '', leagueTag: '' },
  { tag: 'mets', name: 'Мец', country: '', leagueTag: '' },
  { tag: 'vilyareal', name: 'Вильяреал', country: '', leagueTag: '' },
  { tag: 'astonvilla', name: 'Астон Вилла', country: '', leagueTag: '' },
  { tag: 'goa', name: 'Гоа', country: '', leagueTag: '' },
  { tag: 'vestkhem', name: 'Вест Хэм', country: '', leagueTag: '' },
  { tag: 'nant', name: 'Нант', country: '', leagueTag: '' },
  { tag: 'al-garafa', name: 'Аль-Гарафа', country: '', leagueTag: '' },
  { tag: 'katarsk', name: 'Катар СК', country: '', leagueTag: '' },
  { tag: 'monpele', name: 'Монпелье', country: '', leagueTag: '' },
  { tag: 'nim', name: 'Ним', country: '', leagueTag: '' },
  { tag: 'sent-eten', name: 'Сент-Этьен', country: '', leagueTag: '' },
  { tag: 'oser', name: 'Осер', country: '', leagueTag: '' },
  { tag: 'le-man', name: 'Ле-Ман', country: '', leagueTag: '' },
  { tag: 'gingam', name: 'Гингам', country: '', leagueTag: '' },
  { tag: 'shankhayshenkhua', name: 'Шанхай Шэньхуа', country: '', leagueTag: '' },
  { tag: 'galatasaray', name: 'Галатасарай', country: '', leagueTag: '' },
  { tag: 'monrealimpakt', name: 'Монреаль Импакт', country: '', leagueTag: '' },
  { tag: 'feniksrayzing', name: 'Феникс Райзинг', country: '', leagueTag: '' },
  { tag: 'seltavigo', name: 'Сельта Виго', country: '', leagueTag: '' },
  { tag: 'lidsyunayted', name: 'Лидс Юнайтед', country: '', leagueTag: '' },
  { tag: 'platense', name: 'Платенсе', country: '', leagueTag: '' },
  { tag: 'erkules', name: 'Эркулес', country: '', leagueTag: '' },
  { tag: 'baniyas', name: 'Банияс', country: '', leagueTag: '' },
  { tag: 'riverpleyt', name: 'Ривер Плейт', country: '', leagueTag: '' },
  { tag: 'nyuellsoldboyz', name: 'Ньюэллс Олд Бойз', country: '', leagueTag: '' },
  { tag: 'punesiti', name: 'Пуне Сити', country: '', leagueTag: '' },
  { tag: 'bolton', name: 'Болтон', country: '', leagueTag: '' },
  { tag: 'west-brom', name: 'Вест Бромвич', country: '', leagueTag: '' },
  { tag: 'khemnits', name: 'Хемниц', country: '', leagueTag: '' },
  { tag: 'kayzerslautern', name: 'Кайзерслаутерн', country: '', leagueTag: '' },
  { tag: 'bayerleverkuzen', name: 'Байер Леверкузен', country: '', leagueTag: '' },
  { tag: 'karlsrue', name: 'Карлсруэ', country: '', leagueTag: '' },
  { tag: 'metrostars', name: 'Метростарс', country: '', leagueTag: '' },
  { tag: 'vfbshtutgart', name: 'ВФБ Штутгарт', country: '', leagueTag: '' },
  { tag: 'sampdoria', name: 'Сэмпдория', country: '', leagueTag: '' },
  { tag: 'servett', name: 'Серветт', country: '', leagueTag: '' },
  { tag: 'tsv1861nerdlingen', name: 'ТСВ 1861 Нёрдлинген', country: '', leagueTag: '' },
  { tag: 'nyu-yorkkozmos', name: 'Нью-Йорк Козмос', country: '', leagueTag: '' },
  { tag: 'gamburg', name: 'Гамбург', country: '', leagueTag: '' },
  { tag: 'augsburg', name: 'Аугсбург', country: '', leagueTag: '' },
  { tag: 'deportivo', name: 'Депортиво', country: '', leagueTag: '' },
  { tag: 'kataniya', name: 'Катания', country: '', leagueTag: '' },
  { tag: 'nyu-inglendrevolyushn', name: 'Нью-Инглэнд Революшн', country: '', leagueTag: '' },
  { tag: 'suonsisiti', name: 'Суонси Сити', country: '', leagueTag: '' },
  { tag: 'nyu-yorksiti', name: 'Нью-Йорк Сити', country: '', leagueTag: '' },
  { tag: 'donkasterrovers', name: 'Донкастер Роверс', country: '', leagueTag: '' },
  { tag: 'brondbyu', name: 'Брондбю', country: '', leagueTag: '' },
  { tag: 'nottingham', name: 'Ноттингем Форест', country: '', leagueTag: '' },
  { tag: 'seltik', name: 'Селтик', country: '', leagueTag: '' },
  { tag: 'denbos', name: 'Ден Бос', country: '', leagueTag: '' },
  { tag: 'kheerenven', name: 'Хееренвен', country: '', leagueTag: '' },
  { tag: 'groningen', name: 'Гронинген', country: '', leagueTag: '' },
  { tag: 'nitstsa', name: 'Ницца', country: '', leagueTag: '' },
  { tag: 'orlandositi', name: 'Орландо Сити', country: '', leagueTag: '' },
  { tag: 'keln', name: 'Кельн', country: '', leagueTag: '' },
  { tag: 'valensiya', name: 'Валенсия', country: '', leagueTag: '' },
  { tag: 'vaskodagama', name: 'Васко да Гама', country: '', leagueTag: '' },
  { tag: 'santakruz', name: 'Санта Круз', country: '', leagueTag: '' },
  { tag: 'olimpiakos', name: 'Олимпиакос', country: '', leagueTag: '' },
  { tag: 'aekafiny', name: 'AEK Афины', country: '', leagueTag: '' },
  { tag: 'kraisense', name: 'Краисьенсе', country: '', leagueTag: '' },
  { tag: 'san-paulu', name: 'Сан-Паулу', country: '', leagueTag: '' },
  { tag: 'undiaosan-zhuan', name: 'Ундиао Сан-Жуан', country: '', leagueTag: '' },
  { tag: 'palmeyras', name: 'Палмейрас', country: '', leagueTag: '' },
  { tag: 'anzhi', name: 'Анжи', country: '', leagueTag: '' },
  { tag: 'delhi-dynamos', name: 'Дели Динамос', country: '', leagueTag: '' },
  { tag: 'fiorentina', name: 'Фиорентина', country: '', leagueTag: '' },
  { tag: 'realbetis', name: 'Реал Бетис', country: '', leagueTag: '' },
  { tag: 'saragosa', name: 'Сарагоса', country: '', leagueTag: '' },
  { tag: 'shalke04', name: 'Шальке 04', country: '', leagueTag: '' },
  { tag: 'yuniondeportivasalamanka', name: 'Юнион Депортива Саламанка', country: '', leagueTag: '' },
  { tag: 'cherkezoser', name: 'Черкез Осер', country: '', leagueTag: '' },
  { tag: 'argentinoskhuniors', name: 'Аргентинос Хуниорс', country: '', leagueTag: '' },
  { tag: 'bokakhuniors', name: 'Бока Хуниорс', country: '', leagueTag: '' },
  { tag: 'atletikutukuman', name: 'Атлетику Тукуман', country: '', leagueTag: '' },
  { tag: 'independente', name: 'Индепендьенте', country: '', leagueTag: '' },
  { tag: 'kordekhesus', name: 'Кор. де Хесус', country: '', leagueTag: '' },
  { tag: 'banfild', name: 'Банфилд', country: '', leagueTag: '' },
  { tag: 'rasingklub', name: 'Расинг Клуб', country: '', leagueTag: '' },
  { tag: 'los-andzhelesatsteks', name: 'Лос-Анджелес Ацтекс', country: '', leagueTag: '' },
  { tag: 'vashingtondiplomats', name: 'Вашингтон Дипломатс', country: '', leagueTag: '' },
  { tag: 'rktsvalveyk', name: 'РКЦ Валвейк', country: '', leagueTag: '' },
  { tag: 'reyndzhers', name: 'Рейнджерс', country: '', leagueTag: '' },
  { tag: 'sidney', name: 'Сидней', country: '', leagueTag: '' },
  { tag: 'breshia', name: 'Брешиа', country: '', leagueTag: '' },
  { tag: 'redzhina', name: 'Реджина', country: '', leagueTag: '' },
  { tag: 'aleksandriya', name: 'Александрия', country: '', leagueTag: '' },
  { tag: 'lechche', name: 'Лечче', country: '', leagueTag: '' },
  { tag: 'sportingkhikhon', name: 'Спортинг Хихон', country: '', leagueTag: '' },
  { tag: 'realsaragosa', name: 'Реал Сарагоса', country: '', leagueTag: '' },
  { tag: 'eybar', name: 'Эйбар', country: '', leagueTag: '' },
  { tag: 'seuta', name: 'Сеута', country: '', leagueTag: '' },
  { tag: 'vik', name: 'Вик', country: '', leagueTag: '' },
  { tag: 'realsosedad', name: 'Реал Сосьедад', country: '', leagueTag: '' },
  { tag: 'leysha', name: 'Лейша', country: '', leagueTag: '' },
  { tag: 'fulkhem', name: 'Фулхэм', country: '', leagueTag: '' },
  { tag: 'natal', name: 'Натал', country: '', leagueTag: '' },
  { tag: 'beshiktash', name: 'Бешикташ', country: '', leagueTag: '' },
  { tag: 'nasonal', name: 'Насьональ', country: '', leagueTag: '' },
  { tag: 'krusasul', name: 'Крус Асуль', country: '', leagueTag: '' },
  { tag: 'danubio', name: 'Данубио', country: '', leagueTag: '' },
  { tag: 'kagliari', name: 'Каглиари', country: '', leagueTag: '' },
  { tag: 'dinamozagreb', name: 'Динамо Загреб', country: '', leagueTag: '' },
  { tag: 'shalke', name: 'Шальке', country: '', leagueTag: '' },
  { tag: 'khayduksplit', name: 'Хайдук Сплит', country: '', leagueTag: '' },
  { tag: 'aries', name: 'Ариес', country: '', leagueTag: '' },
  { tag: 'shakhterdonetsk', name: 'Шахтёр Донецк', country: '', leagueTag: '' },
  { tag: 'trabzonspor', name: 'Трабзонспор', country: '', leagueTag: '' },
  { tag: 'orense', name: 'Оренсе', country: '', leagueTag: '' },
  { tag: 'standarlezh', name: 'Стандар Льеж', country: '', leagueTag: '' },
  { tag: 'anderlekht', name: 'Андерлехт', country: '', leagueTag: '' },
  { tag: 'tuluza', name: 'Тулуза', country: '', leagueTag: '' },
  { tag: 'bryugge', name: 'Брюгге', country: '', leagueTag: '' },
  { tag: 'verderbremen', name: 'Вердер Бремен', country: '', leagueTag: '' },
  { tag: 'leganes', name: 'Леганес', country: '', leagueTag: '' },
  { tag: 'espanol', name: 'Эспаньол', country: '', leagueTag: '' },
  { tag: 'malorka', name: 'Мальорка', country: '', leagueTag: '' },
  { tag: 'antalyaspor', name: 'Антальяспор', country: '', leagueTag: '' },
  { tag: 'konyaspor', name: 'Коньяспор', country: '', leagueTag: '' },
  { tag: 'uotford', name: 'Уотфорд', country: '', leagueTag: '' },
  { tag: 'cska-moscow', name: 'ЦСКА Москва', country: '', leagueTag: '' },
  { tag: 'asecmimozas', name: 'ASEC Мимозас', country: '', leagueTag: '' },
  { tag: 'bernli', name: 'Бёрнли', country: '', leagueTag: '' },
  { tag: 'beveren', name: 'Беверен', country: '', leagueTag: '' },
  { tag: 'metalurgdonetsk', name: 'Металург Донецк', country: '', leagueTag: '' },
  { tag: 'loryan', name: 'Лорьян', country: '', leagueTag: '' },
  { tag: 'renn', name: 'Ренн', country: '', leagueTag: '' },
  { tag: 'atletikbilbao', name: 'Атлетик Бильбао', country: '', leagueTag: '' },
  { tag: 'nansi', name: 'Нанси', country: '', leagueTag: '' },
  { tag: 'ruan', name: 'Руан', country: '', leagueTag: '' },
  { tag: 'torino', name: 'Торино', country: '', leagueTag: '' },
  { tag: 'montsa', name: 'Монца', country: '', leagueTag: '' },
  { tag: 'bolonya', name: 'Болонья', country: '', leagueTag: '' },
  { tag: 'avellino', name: 'Авеллино', country: '', leagueTag: '' },
  { tag: 'peskara', name: 'Пескара', country: '', leagueTag: '' },
  { tag: 'sautgempton', name: 'Саутгемптон', country: '', leagueTag: '' },
  { tag: 'blekbernrovers', name: 'Блэкберн Роверс', country: '', leagueTag: '' },
  { tag: 'karlaylyunayted', name: 'Карлайл Юнайтед', country: '', leagueTag: '' },
  { tag: 'middlesbrough', name: 'Мидлсбро', country: '', leagueTag: '' },
  { tag: 'alnviktaun', name: 'Алнвик Таун', country: '', leagueTag: '' },
  { tag: 'uestkhem', name: 'Уэст Хэм', country: '', leagueTag: '' },
  { tag: 'molde', name: 'Молде', country: '', leagueTag: '' },
  { tag: 'altay', name: 'Алтай', country: '', leagueTag: '' },
  { tag: 'braga', name: 'Брага', country: '', leagueTag: '' },
  { tag: 'fenikash', name: 'Феникаш', country: '', leagueTag: '' },
  { tag: 'stouksiti', name: 'Стоук Сити', country: '', leagueTag: '' },
  { tag: 'dsyunayted', name: 'ДС Юнайтед', country: '', leagueTag: '' },
  { tag: 'perudzha', name: 'Перуджа', country: '', leagueTag: '' },
  { tag: 'messina', name: 'Мессина', country: '', leagueTag: '' },
  { tag: 'estudiantes', name: 'Эстудиантес', country: '', leagueTag: '' },
  { tag: 'stremsgodset', name: 'Стремсгодсет', country: '', leagueTag: '' },
  { tag: 'genuya', name: 'Генуя', country: '', leagueTag: '' },
  { tag: 'vardar', name: 'Вардар', country: '', leagueTag: '' },
  { tag: 'legiya', name: 'Легия', country: '', leagueTag: '' },
  { tag: 'taleres', name: 'Тальерес', country: '', leagueTag: '' },
  { tag: 'al-sadd', name: 'Аль-Садд', country: '', leagueTag: '' },
  { tag: 'tenerife', name: 'Тенерифе', country: '', leagueTag: '' },
  { tag: 'rayavalekano', name: 'Рая Вальекано', country: '', leagueTag: '' },
  { tag: 'atletikonasonal', name: 'Атлетико Насьональ', country: '', leagueTag: '' },
  { tag: 'penyarol', name: 'Пеньяроль', country: '', leagueTag: '' },
  { tag: 'bolivar', name: 'Боливар', country: '', leagueTag: '' },
  { tag: 'sportingkali', name: 'Спортинг Кали', country: '', leagueTag: '' },
  { tag: 'grasskhoppers', name: 'Грассхопперс', country: '', leagueTag: '' },
  { tag: 'sakaryaspor', name: 'Сакарьяспор', country: '', leagueTag: '' },
  { tag: 'zenit', name: 'Зенит', country: '', leagueTag: '' },
  { tag: 'krasnodar', name: 'Краснодар', country: '', leagueTag: '' },
  { tag: 'spartak', name: 'Спартак', country: '', leagueTag: '' },
  { tag: 'lokomotiv', name: 'Локомотив', country: '', leagueTag: '' },
  { tag: 'portsmut', name: 'Портсмут', country: '', leagueTag: '' },
  { tag: 'satonsiti', name: 'Сатон Сити', country: '', leagueTag: '' },
  { tag: 'dinamomoskva', name: 'Динамо Москва', country: '', leagueTag: '' },
  { tag: 'dinamokiev', name: 'Динамо Киев', country: '', leagueTag: '' },
  { tag: 'kluzh', name: 'Клуж', country: '', leagueTag: '' },
  { tag: 'bastiya', name: 'Бастия', country: '', leagueTag: '' },
  { tag: 'dyamatadio', name: 'Дьяматадио', country: '', leagueTag: '' },
  { tag: 'senegal', name: 'Сенегал', country: '', leagueTag: '' },
  { tag: 'styaua', name: 'Стяуа', country: '', leagueTag: '' },
  { tag: 'vidadkasablanka', name: 'Видад Касабланка', country: '', leagueTag: '' },
  { tag: 'kasasport', name: 'Каса Спорт', country: '', leagueTag: '' },
  { tag: 'malaga', name: 'Малага', country: '', leagueTag: '' },
  { tag: 'kolo-kolo', name: 'Коло-Коло', country: '', leagueTag: '' },
  { tag: 'trenchin', name: 'Тренчин', country: '', leagueTag: '' },
  { tag: 'zhilina', name: 'Жилина', country: '', leagueTag: '' },
  { tag: 'rbleyptsig', name: 'RB Лейпциг', country: '', leagueTag: '' },
  { tag: 'birmingem', name: 'Бирмингем', country: '', leagueTag: '' },
  { tag: 'avryunayted', name: 'Авр Юнайтед', country: '', leagueTag: '' },
  { tag: 'urugvay', name: 'Уругвай', country: '', leagueTag: '' },
  { tag: 'khoffenkhaym', name: 'Хоффенхайм', country: '', leagueTag: '' },
  { tag: 'tsv1861nyordlingen', name: 'ТСВ 1861 Нёрдлинген', country: '', leagueTag: '' },
  { tag: 'shakhtyordonetsk', name: 'Шахтёр Донецк', country: '', leagueTag: '' },
  { tag: 'byornli', name: 'Бёрнли', country: '', leagueTag: '' },
  { tag: 'tours', name: 'Tours', country: '', leagueTag: '' },
  { tag: 'cannes', name: 'Cannes', country: '', leagueTag: '' },
  { tag: 'metz', name: 'Metz', country: '', leagueTag: '' },
  { tag: 'villarreal', name: 'Villarreal', country: '', leagueTag: '' },
  { tag: 'nantes', name: 'Nantes', country: '', leagueTag: '' },
  { tag: 'al-gharafa', name: 'Al-Gharafa', country: '', leagueTag: '' },
  { tag: 'boltonwanderers', name: 'Bolton Wanderers', country: '', leagueTag: '' },
  { tag: 'auxerre', name: 'Auxerre', country: '', leagueTag: '' },
  { tag: 'martigues', name: 'Martigues', country: '', leagueTag: '' },
  { tag: 'montpellier', name: 'Montpellier', country: '', leagueTag: '' },
  { tag: 'nmes', name: 'Nîmes', country: '', leagueTag: '' },
  { tag: 'leedsunited', name: 'Leeds United', country: '', leagueTag: '' },
  { tag: 'hercules', name: 'Hercules', country: '', leagueTag: '' },
  { tag: 'riverplate', name: 'River Plate', country: '', leagueTag: '' },
  { tag: 'punecity', name: 'Pune City', country: '', leagueTag: '' },
  { tag: 'chemnitzerfc', name: 'Chemnitzer FC', country: '', leagueTag: '' },
  { tag: 'kaiserslautern', name: 'Kaiserslautern', country: '', leagueTag: '' },
  { tag: 'bayerleverkusen', name: 'Bayer Leverkusen', country: '', leagueTag: '' },
  { tag: 'karlsruhersc', name: 'Karlsruher SC', country: '', leagueTag: '' },
  { tag: 'newyorkmetrostars', name: 'New York MetroStars', country: '', leagueTag: '' },
  { tag: 'servette', name: 'Servette', country: '', leagueTag: '' },
  { tag: 'fortlauderdalestrikers', name: 'Fort Lauderdale Strikers', country: '', leagueTag: '' },
  { tag: 'hamburg', name: 'Hamburg', country: '', leagueTag: '' },
  { tag: 'newyorkcosmos', name: 'New York Cosmos', country: '', leagueTag: '' },
  { tag: 'westhamunited', name: 'West Ham United', country: '', leagueTag: '' },
  { tag: 'swanseacity', name: 'Swansea City', country: '', leagueTag: '' },
  { tag: 'newyorkcity', name: 'New York City', country: '', leagueTag: '' },
  { tag: 'prestonnorthend', name: 'Preston North End', country: '', leagueTag: '' },
  { tag: 'cobhramblers', name: 'Cobh Ramblers', country: '', leagueTag: '' },
  { tag: 'nottinghamforest', name: 'Nottingham Forest', country: '', leagueTag: '' },
  { tag: 'celtic', name: 'Celtic', country: '', leagueTag: '' },
  { tag: 'denbosch', name: 'Den Bosch', country: '', leagueTag: '' },
  { tag: 'heerenveen', name: 'Heerenveen', country: '', leagueTag: '' },
  { tag: 'mlaga', name: 'Málaga', country: '', leagueTag: '' },
  { tag: 'vascodagama', name: 'Vasco da Gama', country: '', leagueTag: '' },
  { tag: 'miamifc', name: 'Miami FC', country: '', leagueTag: '' },
  { tag: 'adelaideunited', name: 'Adelaide United', country: '', leagueTag: '' },
  { tag: 'santacruz', name: 'Santa Cruz', country: '', leagueTag: '' },
  { tag: 'mogimirim', name: 'Mogi Mirim', country: '', leagueTag: '' },
  { tag: 'corinthians', name: 'Corinthians', country: '', leagueTag: '' },
  { tag: 'palmeiras', name: 'Palmeiras', country: '', leagueTag: '' },
  { tag: 'deportivolacorua', name: 'Deportivo La Coruña', country: '', leagueTag: '' },
  { tag: 'olympiakos', name: 'Olympiakos', country: '', leagueTag: '' },
  { tag: 'aekathens', name: 'AEK Athens', country: '', leagueTag: '' },
  { tag: 'bunyodkor', name: 'Bunyodkor', country: '', leagueTag: '' },
  { tag: 'kabuscorp', name: 'Kabuscorp', country: '', leagueTag: '' },
  { tag: 'uniosojoo', name: 'União São João', country: '', leagueTag: '' },
  { tag: 'fenerbahe', name: 'Fenerbahçe', country: '', leagueTag: '' },
  { tag: 'delhidynamos', name: 'Delhi Dynamos', country: '', leagueTag: '' },
  { tag: 'sopaulo', name: 'São Paulo', country: '', leagueTag: '' },
  { tag: 'realzaragoza', name: 'Real Zaragoza', country: '', leagueTag: '' },
  { tag: 'juventude', name: 'Juventude', country: '', leagueTag: '' },
  { tag: 'schalke04', name: 'Schalke 04', country: '', leagueTag: '' },
  { tag: 'hellasverona', name: 'Hellas Verona', country: '', leagueTag: '' },
  { tag: 'bocajuniors', name: 'Boca Juniors', country: '', leagueTag: '' },
  { tag: 'al-arabi', name: 'Al-Arabi', country: '', leagueTag: '' },
  { tag: 'genoa', name: 'Genoa', country: '', leagueTag: '' },
  { tag: 'eibarloan', name: 'Eibar (loan)', country: '', leagueTag: '' },
  { tag: 'realsociedad', name: 'Real Sociedad', country: '', leagueTag: '' },
  { tag: '1860mnchen', name: '1860 München', country: '', leagueTag: '' },
  { tag: 'werderbremen', name: 'Werder Bremen', country: '', leagueTag: '' },
  { tag: 'istanbulbaakehir', name: 'İstanbul Başakşehir', country: '', leagueTag: '' },
  { tag: 'nancy', name: 'Nancy', country: '', leagueTag: '' },
  { tag: 'saint-tienne', name: 'Saint-Étienne', country: '', leagueTag: '' },
  { tag: 'valenciennes', name: 'Valenciennes', country: '', leagueTag: '' },
  { tag: 'clubbrugge', name: 'Club Brugge', country: '', leagueTag: '' },
  { tag: 'gueugnon', name: 'Gueugnon', country: '', leagueTag: '' },
  { tag: 'prato', name: 'Prato', country: '', leagueTag: '' },
  { tag: 'pisa', name: 'Pisa', country: '', leagueTag: '' },
  { tag: 'ravenna', name: 'Ravenna', country: '', leagueTag: '' },
  { tag: 'venezia', name: 'Venezia', country: '', leagueTag: '' },
  { tag: 'atalanta', name: 'Atalanta', country: '', leagueTag: '' },
  { tag: 'vicenza', name: 'Vicenza', country: '', leagueTag: '' },
  { tag: 'bologna', name: 'Bologna', country: '', leagueTag: '' },
  { tag: 'brescia', name: 'Brescia', country: '', leagueTag: '' },
  { tag: 'southampton', name: 'Southampton', country: '', leagueTag: '' },
  { tag: 'blackburnrovers', name: 'Blackburn Rovers', country: '', leagueTag: '' },
  { tag: 'salgueiros', name: 'Salgueiros', country: '', leagueTag: '' },
  { tag: 'stokecity', name: 'Stoke City', country: '', leagueTag: '' },
  { tag: 'millonarios', name: 'Millonarios', country: '', leagueTag: '' },
  { tag: 'espanyol', name: 'Espanyol', country: '', leagueTag: '' },
  { tag: 'svaspern', name: 'SV Aspern', country: '', leagueTag: '' },
  { tag: 'austriawien', name: 'Austria Wien', country: '', leagueTag: '' },
  { tag: 'fcbayernmnchen', name: 'FC Bayern München', country: '', leagueTag: '' },
  { tag: 'tsghoffenheim', name: 'TSG Hoffenheim', country: '', leagueTag: '' },
  { tag: 'honvd', name: 'Honvéd', country: '', leagueTag: '' },
  { tag: 'monterrey', name: 'Monterrey', country: '', leagueTag: '' },
  { tag: 'torontometros', name: 'Toronto Metros', country: '', leagueTag: '' },
  { tag: 'fulham', name: 'Fulham', country: '', leagueTag: '' },
  { tag: 'hibernian', name: 'Hibernian', country: '', leagueTag: '' },
  { tag: 'losangelesaztecs', name: 'Los Angeles Aztecs', country: '', leagueTag: '' },
  { tag: 'washingtondiplomats', name: 'Washington Diplomats', country: '', leagueTag: '' },
  { tag: 'levante', name: 'Levante', country: '', leagueTag: '' },
  { tag: 'vorwrtssteyr', name: 'Vorwärts Steyr', country: '', leagueTag: '' },
  { tag: 'eintrachtbraunschweig', name: 'Eintracht Braunschweig', country: '', leagueTag: '' },
  { tag: 'leicestercity', name: 'Leicester City', country: '', leagueTag: '' },
  { tag: 'nagoyagrampus', name: 'Nagoya Grampus', country: '', leagueTag: '' },
  { tag: 'hfchaarlem', name: 'HFC Haarlem', country: '', leagueTag: '' },
  { tag: 'tsskasofiya', name: 'ЦСКА София', country: '', leagueTag: '' },
  { tag: 'cruzazul', name: 'Cruz Azul', country: '', leagueTag: '' },
  { tag: 'dcunited', name: 'DC United', country: '', leagueTag: '' },
  { tag: 'tonnerreyaound', name: 'Tonnerre Yaoundé', country: '', leagueTag: '' },
  { tag: 'africasports', name: 'Africa Sports', country: '', leagueTag: '' },
  { tag: 'al-jazira', name: 'Al-Jazira', country: '', leagueTag: '' },
  { tag: 'dynamodresden', name: 'Dynamo Dresden', country: '', leagueTag: '' },
  { tag: 'vfbstuttgart', name: 'VfB Stuttgart', country: '', leagueTag: '' },
  { tag: 'duklaprague', name: 'Dukla Prague', country: '', leagueTag: '' },
  { tag: 'spartaprague', name: 'Sparta Prague', country: '', leagueTag: '' },
  { tag: 'argentinosjuniors', name: 'Argentinos Juniors', country: '', leagueTag: '' },
  { tag: 'talleres', name: 'Talleres', country: '', leagueTag: '' },
  { tag: 'banfield', name: 'Banfield', country: '', leagueTag: '' },
  { tag: 'santos', name: 'Santos', country: '', leagueTag: '' },
  { tag: 'botafogo', name: 'Botafogo', country: '', leagueTag: '' },
  { tag: 'sumitomometals', name: 'Sumitomo Metals', country: '', leagueTag: '' },
  { tag: 'brndby', name: 'Brøndby', country: '', leagueTag: '' },
  { tag: 'visselkobe', name: 'Vissel Kobe', country: '', leagueTag: '' },
  { tag: 'gladsaxe-hero', name: 'Gladsaxe-Hero', country: '', leagueTag: '' },
  { tag: 'hvidovre', name: 'Hvidovre', country: '', leagueTag: '' },
  { tag: 'scunthorpeunited', name: 'Scunthorpe United', country: '', leagueTag: '' },
  { tag: 'lens', name: 'Lens', country: '', leagueTag: '' },
  { tag: 'montrealimpact', name: 'Montreal Impact', country: '', leagueTag: '' },
  { tag: 'crystalpalace', name: 'Crystal Palace', country: '', leagueTag: '' },
  { tag: 'shenzhen', name: 'Shenzhen', country: '', leagueTag: '' },
  { tag: 'rennes', name: 'Rennes', country: '', leagueTag: '' },
  { tag: 'alnassr', name: 'Al Nassr', country: '', leagueTag: '' },
  { tag: 'intermiami', name: 'Inter Miami', country: '', leagueTag: '' },
  { tag: 'fcschalke04', name: 'FC Schalke 04', country: '', leagueTag: '' },
  { tag: 'nacional', name: 'Nacional', country: '', leagueTag: '' },
  { tag: 'grmio', name: 'Grêmio', country: '', leagueTag: '' },
  { tag: 'zniczpruszkw', name: 'Znicz Pruszków', country: '', leagueTag: '' },
  { tag: 'lechpozna', name: 'Lech Poznań', country: '', leagueTag: '' },
  { tag: 'alhilal', name: 'Al Hilal', country: '', leagueTag: '' },
  { tag: 'olympiacos', name: 'Olympiacos', country: '', leagueTag: '' },
  { tag: 'alittihad', name: 'Al Ittihad', country: '', leagueTag: '' },
  { tag: 'krcgenk', name: 'KRC Genk', country: '', leagueTag: '' },
  { tag: 'olimpijaljubljana', name: 'Olimpija Ljubljana', country: '', leagueTag: '' },
  { tag: 'rioave', name: 'Rio Ave', country: '', leagueTag: '' },
  { tag: 'bryne', name: 'Bryne', country: '', leagueTag: '' },
  { tag: 'redbullsalzburg', name: 'Red Bull Salzburg', country: '', leagueTag: '' },
  { tag: 'fcgroningen', name: 'FC Groningen', country: '', leagueTag: '' },
  { tag: 'malmff', name: 'Malmö FF', country: '', leagueTag: '' },
  { tag: 'losangelesfc', name: 'Los Angeles FC', country: '', leagueTag: '' },
  { tag: 'cerro', name: 'Cerro', country: '', leagueTag: '' },
  { tag: 'cagliari', name: 'Cagliari', country: '', leagueTag: '' },
  { tag: 'vlezsarsfield', name: 'Vélez Sarsfield', country: '', leagueTag: '' },
  { tag: 'herthabsc', name: 'Hertha BSC', country: '', leagueTag: '' },
  { tag: 'hamburgersv', name: 'Hamburger SV', country: '', leagueTag: '' },
  { tag: 'salernitana', name: 'Salernitana', country: '', leagueTag: '' },
  { tag: 'genk', name: 'Genk', country: '', leagueTag: '' },
  { tag: 'gironafc', name: 'Girona FC', country: '', leagueTag: '' },
  { tag: 'leytonorient', name: 'Leyton Orient', country: '', leagueTag: '' },
  { tag: 'millwall', name: 'Millwall', country: '', leagueTag: '' },
  { tag: 'norwichcity', name: 'Norwich City', country: '', leagueTag: '' },
  { tag: 'willemii', name: 'Willem II', country: '', leagueTag: '' },
  { tag: 'almokawloon', name: 'Al Mokawloon', country: '', leagueTag: '' },
  { tag: 'basel', name: 'Basel', country: '', leagueTag: '' },
  { tag: 'internacional', name: 'Internacional', country: '', leagueTag: '' },
  { tag: 'usboulogne', name: 'US Boulogne', country: '', leagueTag: '' },
  { tag: 'smcaen', name: 'SM Caen', country: '', leagueTag: '' },
  { tag: 'emiratesclub', name: 'Emirates Club', country: '', leagueTag: '' },
  { tag: 'livorno', name: 'Livorno', country: '', leagueTag: '' },
  { tag: 'independiente', name: 'Independiente', country: '', leagueTag: '' },
  { tag: 'rsfutebol', name: 'RS Futebol', country: '', leagueTag: '' },
  { tag: 'dinamomoscow', name: 'Dinamo Moscow', country: '', leagueTag: '' },
  { tag: 'palermo', name: 'Palermo', country: '', leagueTag: '' },
  { tag: 'cobreloa', name: 'Cobreloa', country: '', leagueTag: '' },
  { tag: 'mlagacf', name: 'Málaga CF', country: '', leagueTag: '' },
  { tag: 'fcseoul', name: 'FC Seoul', country: '', leagueTag: '' },
  { tag: 'bayer04leverkusen', name: 'Bayer 04 Leverkusen', country: '', leagueTag: '' },
  { tag: 'institutoacc', name: 'Instituto ACC', country: '', leagueTag: '' },
  { tag: 'rbleipzig', name: 'RB Leipzig', country: '', leagueTag: '' },
  { tag: 'guangzhouevergrande', name: 'Guangzhou Evergrande', country: '', leagueTag: '' },
  { tag: 'alahlijeddah', name: 'Al Ahli Jeddah', country: '', leagueTag: '' },
  { tag: 'spartapraha', name: 'Sparta Praha', country: '', leagueTag: '' },
  { tag: 'martimo', name: 'Marítimo', country: '', leagueTag: '' },
  { tag: 'beikta', name: 'Beşiktaş', country: '', leagueTag: '' },
  { tag: 'chicagofire', name: 'Chicago Fire', country: '', leagueTag: '' },
  { tag: 'olympiquemarseille', name: 'Olympique Marseille', country: '', leagueTag: '' },
  { tag: 'domale', name: 'Domžale', country: '', leagueTag: '' },
  { tag: 'lancerosboyac', name: 'Lanceros Boyacá', country: '', leagueTag: '' },
  { tag: 'rayovallecano', name: 'Rayo Vallecano', country: '', leagueTag: '' },
  { tag: 'ogcnice', name: 'OGC Nice', country: '', leagueTag: '' },
  { tag: 'treviso', name: 'Treviso', country: '', leagueTag: '' },
  { tag: 'bari', name: 'Bari', country: '', leagueTag: '' },
  { tag: 'unionberlin', name: 'Union Berlin', country: '', leagueTag: '' },
  { tag: 'rotweissahlen', name: 'Rot Weiss Ahlen', country: '', leagueTag: '' },
  { tag: 'dijon', name: 'Dijon', country: '', leagueTag: '' },
  { tag: 'al-qadsiah', name: 'Al-Qadsiah', country: '', leagueTag: '' },
  { tag: 'al-duhail', name: 'Al-Duhail', country: '', leagueTag: '' },
  { tag: 'brentford', name: 'Brentford', country: '', leagueTag: '' },
  { tag: 'anderlecht', name: 'Anderlecht', country: '', leagueTag: '' },
  { tag: 'westbromwichalbion', name: 'West Bromwich Albion', country: '', leagueTag: '' },
  { tag: 'saprissa', name: 'Saprissa', country: '', leagueTag: '' },
  { tag: 'albacete', name: 'Albacete', country: '', leagueTag: '' },
  { tag: 'unampumas', name: 'UNAM Pumas', country: '', leagueTag: '' },
  { tag: 'lehavre', name: 'Le Havre', country: '', leagueTag: '' },
  { tag: 'foggia', name: 'Foggia', country: '', leagueTag: '' },
  { tag: 'pescara', name: 'Pescara', country: '', leagueTag: '' },
  { tag: 'torontofc', name: 'Toronto FC', country: '', leagueTag: '' },
  { tag: 'envigado', name: 'Envigado', country: '', leagueTag: '' },
  { tag: 'al-rayyan', name: 'Al-Rayyan', country: '', leagueTag: '' },
  { tag: 'len', name: 'León', country: '', leagueTag: '' },
  { tag: 'minnesotaunited', name: 'Minnesota United', country: '', leagueTag: '' },
  { tag: 'queensparkrangers', name: 'Queens Park Rangers', country: '', leagueTag: '' },
  { tag: 'barreirense', name: 'Barreirense', country: '', leagueTag: '' },
  { tag: 'boavista', name: 'Boavista', country: '', leagueTag: '' },
  { tag: 'novara', name: 'Novara', country: '', leagueTag: '' },
  { tag: 'ultimatestrikersacademy', name: 'Ultimate Strikers Academy', country: '', leagueTag: '' },
  { tag: 'charleroi', name: 'Charleroi', country: '', leagueTag: '' },
  { tag: 'pearol', name: 'Peñarol', country: '', leagueTag: '' },
  { tag: 'deportivodelacorua', name: 'Deportivo de La Coruña', country: '', leagueTag: '' },
  { tag: 'atlticoparanaense', name: 'Atlético Paranaense', country: '', leagueTag: '' },
  { tag: 'shakhtardonetsk', name: 'Shakhtar Donetsk', country: '', leagueTag: '' },
  { tag: 'fcbasel', name: 'FC Basel', country: '', leagueTag: '' },
  { tag: 'al-shabab', name: 'Al-Shabab', country: '', leagueTag: '' },
  { tag: 'slovanbratislava', name: 'Slovan Bratislava', country: '', leagueTag: '' },
  { tag: 'dalianprofessional', name: 'Dalian Professional', country: '', leagueTag: '' },
  { tag: 'ifkgteborg', name: 'IFK Göteborg', country: '', leagueTag: '' },
  { tag: 'agovvapeldoorn', name: 'AGOVV Apeldoorn', country: '', leagueTag: '' },
  { tag: 'utrecht', name: 'Utrecht', country: '', leagueTag: '' },
  { tag: 'colo-colo', name: 'Colo-Colo', country: '', leagueTag: '' },
  { tag: 'athleticoparanaense', name: 'Athletico Paranaense', country: '', leagueTag: '' },
  { tag: 'rosariocentral', name: 'Rosario Central', country: '', leagueTag: '' },
  { tag: 'beerschot', name: 'Beerschot', country: '', leagueTag: '' },
  { tag: 'royalantwerp', name: 'Royal Antwerp', country: '', leagueTag: '' },
  { tag: 'legiawarszawa', name: 'Legia Warszawa', country: '', leagueTag: '' },
  { tag: 'hospitalet', name: 'Hospitalet', country: '', leagueTag: '' },
  { tag: 'cornell', name: 'Cornellà', country: '', leagueTag: '' },
  { tag: 'vancouverwhitecaps', name: 'Vancouver Whitecaps', country: '', leagueTag: '' },
  { tag: 'sorrento', name: 'Sorrento', country: '', leagueTag: '' },
  { tag: 'juvestabia', name: 'Juve Stabia', country: '', leagueTag: '' },
  { tag: 'parisfc', name: 'Paris FC', country: '', leagueTag: '' },
  { tag: 'figueirense', name: 'Figueirense', country: '', leagueTag: '' },
  { tag: 'lecce', name: 'Lecce', country: '', leagueTag: '' },
  { tag: 'paulnia', name: 'Paulínia', country: '', leagueTag: '' },
  { tag: 'realmadridcastilla', name: 'Real Madrid Castilla', country: '', leagueTag: '' },
  { tag: 'vflbochum', name: 'VfL Bochum', country: '', leagueTag: '' },
  { tag: 'avironbayonnais', name: 'Aviron Bayonnais', country: '', leagueTag: '' },
  { tag: 'athleticclub', name: 'Athletic Club', country: '', leagueTag: '' },
  { tag: 'dundeeunited', name: 'Dundee United', country: '', leagueTag: '' },
  { tag: 'hullcity', name: 'Hull City', country: '', leagueTag: '' },
  { tag: 'strmsgodset', name: 'Strømsgodset', country: '', leagueTag: '' },
  { tag: 'herenveen', name: 'Herenveen', country: '', leagueTag: '' },
  { tag: 'vitesse', name: 'Vitesse', country: '', leagueTag: '' },
  { tag: 'racingclub', name: 'Racing Club', country: '', leagueTag: '' },
  { tag: 'osasuna', name: 'Osasuna', country: '', leagueTag: '' },
  { tag: 'athleticbilbao', name: 'Athletic Bilbao', country: '', leagueTag: '' },
  { tag: 'qatarsc', name: 'Qatar SC', country: '', leagueTag: '' },
  { tag: 'asecmimosas', name: 'ASEC Mimosas', country: '', leagueTag: '' },
  { tag: 'metalurhdonetsk', name: 'Metalurh Donetsk', country: '', leagueTag: '' },
  { tag: 'derbycounty', name: 'Derby County', country: '', leagueTag: '' },
  { tag: 'pistoiese', name: 'Pistoiese', country: '', leagueTag: '' },
  { tag: 'ascoli', name: 'Ascoli', country: '', leagueTag: '' },
  { tag: 'shanghaishenhua', name: 'Shanghai Shenhua', country: '', leagueTag: '' },
  { tag: 'arsenaldesarand', name: 'Arsenal de Sarandí', country: '', leagueTag: '' },
  { tag: 'sanlorenzo', name: 'San Lorenzo', country: '', leagueTag: '' },
  { tag: 'catania', name: 'Catania', country: '', leagueTag: '' },
  { tag: 'monza', name: 'Monza', country: '', leagueTag: '' },
  { tag: 'realoviedo', name: 'Real Oviedo', country: '', leagueTag: '' },
  { tag: 'recreativohuelva', name: 'Recreativo Huelva', country: '', leagueTag: '' },
  { tag: 'coritiba', name: 'Coritiba', country: '', leagueTag: '' },
  { tag: 'jiangsusuning', name: 'Jiangsu Suning', country: '', leagueTag: '' },
  { tag: 'troyes', name: 'Troyes', country: '', leagueTag: '' },
  { tag: 'ecjuventude', name: 'EC Juventude', country: '', leagueTag: '' },
  { tag: 'empoli', name: 'Empoli', country: '', leagueTag: '' },
  { tag: 'assaint-tienne', name: 'AS Saint-Étienne', country: '', leagueTag: '' },
  { tag: 'fatihkaragmrk', name: 'Fatih Karagümrük', country: '', leagueTag: '' },
  { tag: 'grasshopper', name: 'Grasshopper', country: '', leagueTag: '' },
  { tag: 'piacenza', name: 'Piacenza', country: '', leagueTag: '' },
  { tag: 'spal', name: 'Spal', country: '', leagueTag: '' },
  { tag: 'barcelonaesportivocapela', name: 'Barcelona Esportivo Capela', country: '', leagueTag: '' },
  { tag: 'celtavigoloan', name: 'Celta Vigo (loan)', country: '', leagueTag: '' },
  { tag: 'albaceteloan', name: 'Albacete (loan)', country: '', leagueTag: '' },
  { tag: 'valladolidloan', name: 'Valladolid (loan)', country: '', leagueTag: '' },
  { tag: 'wolverhamptonwanderers', name: 'Wolverhampton Wanderers', country: '', leagueTag: '' },
  { tag: 'vitoria', name: 'Vitoria', country: '', leagueTag: '' },
  { tag: 'fortaleza', name: 'Fortaleza', country: '', leagueTag: '' },
  { tag: 'pafos', name: 'Pafos', country: '', leagueTag: '' },
  { tag: 'sharjahfc', name: 'Sharjah FC', country: '', leagueTag: '' },
  { tag: 'cskamoscow', name: 'CSKA Moscow', country: '', leagueTag: '' },
  { tag: 'hajduksplit', name: 'Hajduk Split', country: '', leagueTag: '' },
  { tag: 'sochaux', name: 'Sochaux', country: '', leagueTag: '' },
  { tag: 'roeselare', name: 'Roeselare', country: '', leagueTag: '' },
  { tag: 'sunderland', name: 'Sunderland', country: '', leagueTag: '' },
  { tag: 'coventrycityloan', name: 'Coventry City (loan)', country: '', leagueTag: '' },
  { tag: 'al-ettifaq', name: 'Al-Ettifaq', country: '', leagueTag: '' },
  { tag: 'svgelsenkirchen-hessler06', name: 'SV Gelsenkirchen-Hessler 06', country: '', leagueTag: '' },
  { tag: 'eintrachtfrankfurt', name: 'Eintracht Frankfurt', country: '', leagueTag: '' },
  { tag: 'getafe', name: 'Getafe', country: '', leagueTag: '' },
  { tag: 'sydneyfc', name: 'Sydney FC', country: '', leagueTag: '' },
  { tag: 'chievoverona', name: 'Chievo Verona', country: '', leagueTag: '' },
  { tag: 'kolubara', name: 'Kolubara', country: '', leagueTag: '' },
  { tag: 'koice', name: 'Košice', country: '', leagueTag: '' },
  { tag: 'sassuolo', name: 'Sassuolo', country: '', leagueTag: '' },
  { tag: '1899hoffenheim', name: '1899 Hoffenheim', country: '', leagueTag: '' },
  { tag: 'neomsc', name: 'Neom SC', country: '', leagueTag: '' },
  { tag: 'aassarcelles', name: 'AAS Sarcelles', country: '', leagueTag: '' },
  { tag: 'quimperkerfeunteun', name: 'Quimper Kerfeunteun', country: '', leagueTag: '' },
  { tag: 'damm', name: 'Damm', country: '', leagueTag: '' },
  { tag: 'mallorca', name: 'Mallorca', country: '', leagueTag: '' },
  { tag: 'villarrealb', name: 'Villarreal B', country: '', leagueTag: '' },
  { tag: 'stocksbridgeparksteels', name: 'Stocksbridge Park Steels', country: '', leagueTag: '' },
  { tag: 'fchalifaxtown', name: 'FC Halifax Town', country: '', leagueTag: '' },
  { tag: 'fleetwoodtown', name: 'Fleetwood Town', country: '', leagueTag: '' },
  { tag: 'cremonese', name: 'Cremonese', country: '', leagueTag: '' },
  { tag: 'lokomotivazagreb', name: 'Lokomotiva Zagreb', country: '', leagueTag: '' },
  { tag: 'sgwattenscheid09', name: 'SG Wattenscheid 09', country: '', leagueTag: '' },
  { tag: 'vojvodina', name: 'Vojvodina', country: '', leagueTag: '' },
  { tag: 'deportivoalavs', name: 'Deportivo Alavés', country: '', leagueTag: '' },
  { tag: 'pportpodbrezov', name: 'ŽP Šport Podbrezová', country: '', leagueTag: '' },
  { tag: 'mkilina', name: 'MŠK Žilina', country: '', leagueTag: '' },
  { tag: 'cherbourg', name: 'Cherbourg', country: '', leagueTag: '' },
  { tag: 'marseilleb', name: 'Marseille B', country: '', leagueTag: '' },
  { tag: 'reims', name: 'Reims', country: '', leagueTag: '' },
  { tag: 'dinamotbilisi', name: 'Dinamo Tbilisi', country: '', leagueTag: '' },
  { tag: 'rustavi', name: 'Rustavi', country: '', leagueTag: '' },
  { tag: 'locomotivetbilisi', name: 'Locomotive Tbilisi', country: '', leagueTag: '' },
  { tag: 'rubinkazan', name: 'Rubin Kazan', country: '', leagueTag: '' },
  { tag: 'dinamobatumi', name: 'Dinamo Batumi', country: '', leagueTag: '' },
  { tag: 'udlaspalmas', name: 'UD Las Palmas', country: '', leagueTag: '' },
  { tag: 'birminghamcity', name: 'Birmingham City', country: '', leagueTag: '' },
  { tag: 'rentistas', name: 'Rentistas', country: '', leagueTag: '' },
  { tag: 'bostonriver', name: 'Boston River', country: '', leagueTag: '' },
  { tag: 'fcbarcelonab', name: 'FC Barcelona B', country: '', leagueTag: '' },
  { tag: 'chelseayouth', name: 'Chelsea Youth', country: '', leagueTag: '' },
  { tag: 'bayernmnchenii', name: 'Bayern München II', country: '', leagueTag: '' },
  { tag: 'hebeichinafortune', name: 'Hebei China Fortune', country: '', leagueTag: '' },
  { tag: 'bahia', name: 'Bahia', country: '', leagueTag: '' },
  { tag: 'cardiffcityloan', name: 'Cardiff City (loan)', country: '', leagueTag: '' },
  { tag: 'nottscounty', name: 'Notts County', country: '', leagueTag: '' },
  { tag: 'nice', name: 'Nice', country: '', leagueTag: '' },
  { tag: 'ajaxyouth', name: 'Ajax (youth)', country: '', leagueTag: '' },
  { tag: 'guingamp', name: 'Guingamp', country: '', leagueTag: '' },
  { tag: 'lorient', name: 'Lorient', country: '', leagueTag: '' },
  { tag: 'standardlige', name: 'Standard Liège', country: '', leagueTag: '' },
  { tag: 'zenitsaintpetersburg', name: 'Zenit Saint Petersburg', country: '', leagueTag: '' },
  { tag: 'tianjinquanjian', name: 'Tianjin Quanjian', country: '', leagueTag: '' },
  { tag: 'girona', name: 'Girona', country: '', leagueTag: '' },
  { tag: 'westernsydneywanderers', name: 'Western Sydney Wanderers', country: '', leagueTag: '' },
  { tag: 'melbournevictory', name: 'Melbourne Victory', country: '', leagueTag: '' },
  { tag: 'anzhimakhachkala', name: 'Anzhi Makhachkala', country: '', leagueTag: '' },
  { tag: 'eljezniar', name: 'Željezničar', country: '', leagueTag: '' },
  { tag: 'teplice', name: 'Teplice', country: '', leagueTag: '' },
  { tag: 'alettifaq', name: 'Al Ettifaq', country: '', leagueTag: '' },
  { tag: 'paosdeferreira', name: 'Paços de Ferreira', country: '', leagueTag: '' },
  { tag: 'clermontfoot', name: 'Clermont Foot', country: '', leagueTag: '' },
  { tag: 'granada', name: 'Granada', country: '', leagueTag: '' },
  { tag: 'mtkbudapest', name: 'MTK Budapest', country: '', leagueTag: '' },
  { tag: 'herefordunited', name: 'Hereford United', country: '', leagueTag: '' },
  { tag: 'tranmererovers', name: 'Tranmere Rovers', country: '', leagueTag: '' },
  { tag: 'rbsalzburg', name: 'RB Salzburg', country: '', leagueTag: '' },
  { tag: 'manchestercityyouth', name: 'Manchester City (youth)', country: '', leagueTag: '' },
  { tag: 'barnsleyloan', name: 'Barnsley (loan)', country: '', leagueTag: '' },
  { tag: 'burnley', name: 'Burnley', country: '', leagueTag: '' },
  { tag: 'sheffieldunited', name: 'Sheffield United', country: '', leagueTag: '' },
  { tag: 'queensparkrangersloan', name: 'Queens Park Rangers (loan)', country: '', leagueTag: '' },
  { tag: 'astonvillaloan', name: 'Aston Villa (loan)', country: '', leagueTag: '' },
  { tag: 'fcthun', name: 'FC Thun', country: '', leagueTag: '' },
  { tag: 'youngboys', name: 'Young Boys', country: '', leagueTag: '' },
  { tag: 'scfreiburg', name: 'SC Freiburg', country: '', leagueTag: '' },
  { tag: 'stlouiscitysc', name: 'St. Louis City SC', country: '', leagueTag: '' },
  { tag: 'mosirjastrzbie', name: 'MOSiR Jastrzębie', country: '', leagueTag: '' },
  { tag: 'horadadayouth', name: 'Horadada (youth)', country: '', leagueTag: '' },
  { tag: 'realmadridcyouth', name: 'Real Madrid C (youth)', country: '', leagueTag: '' },
  { tag: 'palermoyouth', name: 'Palermo (youth)', country: '', leagueTag: '' },
  { tag: 'piastgliwice', name: 'Piast Gliwice', country: '', leagueTag: '' },
  { tag: 'benevento', name: 'Benevento', country: '', leagueTag: '' },
  { tag: 'cracovia', name: 'Cracovia', country: '', leagueTag: '' },
  { tag: 'huracn', name: 'Huracán', country: '', leagueTag: '' },
  { tag: 'elche', name: 'Elche', country: '', leagueTag: '' },
  { tag: 'zadar', name: 'Zadar', country: '', leagueTag: '' },
  { tag: 'hnkzadar', name: 'HNK Zadar', country: '', leagueTag: '' },
  { tag: 'celtadevigo', name: 'Celta de Vigo', country: '', leagueTag: '' },
  { tag: 'thrasyvoulos', name: 'Thrasyvoulos', country: '', leagueTag: '' },
  { tag: 'panathinaikos', name: 'Panathinaikos', country: '', leagueTag: '' },
  { tag: 'cruzeiro', name: 'Cruzeiro', country: '', leagueTag: '' },
  { tag: 'afcbournemouth', name: 'AFC Bournemouth', country: '', leagueTag: '' },
  { tag: 'barcelonab', name: 'Barcelona B', country: '', leagueTag: '' },
  { tag: 'fcnantes', name: 'FC Nantes', country: '', leagueTag: '' },
  { tag: 'al-wahda', name: 'Al-Wahda', country: '', leagueTag: '' },
  { tag: 'oxfordunited', name: 'Oxford United', country: '', leagueTag: '' },
  { tag: 'sheffieldwednesday', name: 'Sheffield Wednesday', country: '', leagueTag: '' },
  { tag: 'rotherhamunited', name: 'Rotherham United', country: '', leagueTag: '' },
  { tag: 'reading', name: 'Reading', country: '', leagueTag: '' },
  { tag: 'barnsley', name: 'Barnsley', country: '', leagueTag: '' },
  { tag: 'vfbstuttgartyouth', name: 'VfB Stuttgart (youth)', country: '', leagueTag: '' },
  { tag: 'westbromwichalbionloan', name: 'West Bromwich Albion (loan)', country: '', leagueTag: '' },
  { tag: 'tsghoffenheimloan', name: 'TSG Hoffenheim (loan)', country: '', leagueTag: '' },
  { tag: 'alshabab', name: 'Al Shabab', country: '', leagueTag: '' },
  { tag: 'radnikikragujevac', name: 'Radnički Kragujevac', country: '', leagueTag: '' },
  { tag: 'stuttgart', name: 'Stuttgart', country: '', leagueTag: '' },
  { tag: 'scheerenveen', name: 'SC Heerenveen', country: '', leagueTag: '' },
  { tag: 'fctwente', name: 'FC Twente', country: '', leagueTag: '' },
  { tag: 'wydadac', name: 'Wydad AC', country: '', leagueTag: '' },
  { tag: 'atlticomadridb', name: 'Atlético Madrid B', country: '', leagueTag: '' },
  { tag: 'almeraloan', name: 'Almería (loan)', country: '', leagueTag: '' },
  { tag: 'mallorcaloan', name: 'Mallorca (loan)', country: '', leagueTag: '' },
  { tag: 'vitriaguimares', name: 'Vitória Guimarães', country: '', leagueTag: '' },
  { tag: 'juventusloan', name: 'Juventus (loan)', country: '', leagueTag: '' },
  { tag: 'sanjoseearthquakes', name: 'San Jose Earthquakes', country: '', leagueTag: '' },
  { tag: 'reggina', name: 'Reggina', country: '', leagueTag: '' },
  { tag: 'matera', name: 'Matera', country: '', leagueTag: '' },
  { tag: 'asnancy', name: 'AS Nancy', country: '', leagueTag: '' },
  { tag: 'espanyolloan', name: 'Espanyol (loan)', country: '', leagueTag: '' },
  { tag: 'portoloan', name: 'Porto (loan)', country: '', leagueTag: '' },
  { tag: 'barcelonayouth', name: 'Barcelona (youth)', country: '', leagueTag: '' },
  { tag: 'nathanielboysacademy', name: 'Nathaniel Boys Academy', country: '', leagueTag: '' },
  { tag: 'deportivoalavsloan', name: 'Deportivo Alavés (loan)', country: '', leagueTag: '' },
  { tag: 'realsociedadloan', name: 'Real Sociedad (loan)', country: '', leagueTag: '' },
  { tag: 'bohemianspraha', name: 'Bohemians Praha', country: '', leagueTag: '' },
  { tag: 'rbleipzigloan', name: 'RB Leipzig (loan)', country: '', leagueTag: '' },
  { tag: 'borussiadortmundloan', name: 'Borussia Dortmund (loan)', country: '', leagueTag: '' },
  { tag: '1fcklnyouth', name: '1. FC Köln (youth)', country: '', leagueTag: '' },
  { tag: 'vancouverwhitecapsfc', name: 'Vancouver Whitecaps FC', country: '', leagueTag: '' },
  { tag: 'al-akhli', name: 'Аль-Ахли', country: '', leagueTag: '' },
  { tag: 'parizh', name: 'Париж', country: '', leagueTag: '' },
  { tag: 'villarrealcf', name: 'Villarreal CF', country: '', leagueTag: '' },
  { tag: 'al-kadisiya', name: 'Аль-Кадисия', country: '', leagueTag: '' },
  { tag: 'ayntrakhtfrankfurt', name: 'Айнтрахт Франкфурт', country: '', leagueTag: '' },
  { tag: 'selta', name: 'Сельта', country: '', leagueTag: '' },
  { tag: 'beiktajk', name: 'Beşiktaş JK', country: '', leagueTag: '' },
  { tag: 'brayton', name: 'Брайтон', country: '', leagueTag: '' },
  { tag: 'khetafe', name: 'Хетафе', country: '', leagueTag: '' },
  { tag: '1fsvmainz05', name: '1. FSV Mainz 05', country: '', leagueTag: '' },
  { tag: 'kristalpelas', name: 'Кристал Пэлас', country: '', leagueTag: '' },
  { tag: 'shtutgart', name: 'Штутгарт', country: '', leagueTag: '' },
  { tag: 'atlticomineiro', name: 'Atlético Mineiro', country: '', leagueTag: '' },
  { tag: 'clubbruggekv', name: 'Club Brugge KV', country: '', leagueTag: '' },
  { tag: 'alkhaleej', name: 'Al Khaleej', country: '', leagueTag: '' },
  { tag: 'frayburg', name: 'Фрайбург', country: '', leagueTag: '' },
  { tag: 'bornmut', name: 'Борнмут', country: '', leagueTag: '' },
  { tag: 'verder', name: 'Вердер', country: '', leagueTag: '' },
  { tag: 'internasonal', name: 'Интернасьонал', country: '', leagueTag: '' },
  { tag: 'al-feykha', name: 'Аль-Фейха', country: '', leagueTag: '' },
  { tag: 'zhirona', name: 'Жирона', country: '', leagueTag: '' },
  { tag: 'parizhfk', name: 'Париж ФК', country: '', leagueTag: '' },
  { tag: 'alqadsiahfc', name: 'Al Qadsiah FC', country: '', leagueTag: '' },
  { tag: 'alfayha', name: 'Al Fayha', country: '', leagueTag: '' },
  { tag: 'newellsoldboys', name: 'Newell\'s Old Boys', country: '', leagueTag: '' },
  { tag: 'queenspark', name: 'Queen\'s Park', country: '', leagueTag: '' }
];

const TOURNAMENTS = [
  { tag: 'ucl', name: 'UEFA Champions League', type: 'CLUB' as const },
  { tag: 'uel', name: 'UEFA Europa League', type: 'CLUB' as const },
  { tag: 'worldcup-winner', name: 'FIFA World Cup Winner', type: 'NATIONAL' as const },
  { tag: 'worldcup', name: 'FIFA World Cup Participant', type: 'NATIONAL' as const },
  { tag: 'euro', name: 'UEFA European Championship', type: 'NATIONAL' as const },
  { tag: 'copa-america', name: 'Copa América', type: 'NATIONAL' as const },
  { tag: 'afcon', name: 'Africa Cup of Nations', type: 'NATIONAL' as const },
  { tag: 'ballondor', name: "Ballon d'Or", type: 'INDIVIDUAL' as const },
];

const MANAGERS = [
  { tag: 'pep',        name: 'Pep Guardiola',      nationality: 'Spain' },
  { tag: 'ancelotti',  name: 'Carlo Ancelotti',     nationality: 'Italy' },
  { tag: 'ferguson',   name: 'Alex Ferguson',       nationality: 'Scotland' },
  { tag: 'mourinho',   name: 'José Mourinho',       nationality: 'Portugal' },
  { tag: 'klopp',      name: 'Jürgen Klopp',        nationality: 'Germany' },
  { tag: 'zidane',     name: 'Zinedine Zidane',     nationality: 'France' },
  { tag: 'simeone',    name: 'Diego Simeone',       nationality: 'Argentina' },
  { tag: 'wenger',     name: 'Arsène Wenger',       nationality: 'France' },
  { tag: 'del-bosque', name: 'Vicente del Bosque',  nationality: 'Spain' },
  { tag: 'luis-enrique', name: 'Luis Enrique',      nationality: 'Spain' },
  { tag: 'conte',      name: 'Antonio Conte',       nationality: 'Italy' },
  { tag: 'tuchel',     name: 'Thomas Tuchel',       nationality: 'Germany' },
  { tag: 'flick',      name: 'Hans-Dieter Flick',   nationality: 'Germany' },
  { tag: 'capello',    name: 'Fabio Capello',       nationality: 'Italy' },
  { tag: 'heynckes',   name: 'Jupp Heynckes',       nationality: 'Germany' },
];

import { PLAYERS } from './curatedPlayers.js';

// ─────────────────────────────────────────────
// Seed function
// ─────────────────────────────────────────────
async function main() {
  console.log('🌱 Starting seed...');

  // Upsert leagues
  console.log('  → Seeding leagues...');
  for (const league of LEAGUES) {
    await prisma.league.upsert({
      where: { tag: league.tag },
      update: { name: league.name, country: league.country },
      create: { tag: league.tag, name: league.name, country: league.country },
    });
  }

  // Upsert clubs
  console.log('  → Seeding clubs...');
  for (const club of CLUBS) {
    const league = club.leagueTag
      ? await prisma.league.findUnique({ where: { tag: club.leagueTag } })
      : null;

    await prisma.club.upsert({
      where: { tag: club.tag },
      update: { name: club.name, country: club.country, leagueId: league?.id },
      create: { tag: club.tag, name: club.name, country: club.country, leagueId: league?.id },
    });
  }

  // Upsert tournaments
  console.log('  → Seeding tournaments...');
  for (const t of TOURNAMENTS) {
    await prisma.tournament.upsert({
      where: { tag: t.tag },
      update: { name: t.name, type: t.type },
      create: { tag: t.tag, name: t.name, type: t.type },
    });
  }

  // Upsert managers
  console.log('  → Seeding managers...');
  for (const m of MANAGERS) {
    await prisma.manager.upsert({
      where: { tag: m.tag },
      update: { name: m.name, nationality: m.nationality },
      create: { tag: m.tag, name: m.name, nationality: m.nationality },
    });
  }

  // Upsert players with all their relations
  console.log('  → Seeding players...');
  for (const p of PLAYERS) {
    const player = await prisma.player.upsert({
      where: { id: p.id },
      update: {
        name: p.name,
        aliases: p.aliases,
        nationality: p.nationality,
        position: p.position,
      },
      create: {
        id: p.id,
        name: p.name,
        aliases: p.aliases,
        nationality: p.nationality,
        position: p.position,
      },
    });

    // Link clubs
    for (const clubTag of p.clubs) {
      const club = await prisma.club.findUnique({ where: { tag: clubTag } });
      if (club) {
        await prisma.playerClub.upsert({
          where: { playerId_clubId: { playerId: player.id, clubId: club.id } },
          update: {},
          create: { playerId: player.id, clubId: club.id },
        });
      }
    }

    // Link leagues
    for (const leagueTag of p.leagues) {
      const league = await prisma.league.findUnique({ where: { tag: leagueTag } });
      if (league) {
        await prisma.playerLeague.upsert({
          where: { playerId_leagueId: { playerId: player.id, leagueId: league.id } },
          update: {},
          create: { playerId: player.id, leagueId: league.id },
        });
      }
    }

    // Link managers
    for (const managerTag of p.managers) {
      const manager = await prisma.manager.findUnique({ where: { tag: managerTag } });
      if (manager) {
        await prisma.playerManager.upsert({
          where: { playerId_managerId: { playerId: player.id, managerId: manager.id } },
          update: {},
          create: { playerId: player.id, managerId: manager.id },
        });
      }
    }

    // Link tournaments
    for (const tournamentTag of p.tournaments) {
      const tournament = await prisma.tournament.findUnique({ where: { tag: tournamentTag } });
      if (tournament) {
        await prisma.playerTournament.upsert({
          where: { playerId_tournamentId: { playerId: player.id, tournamentId: tournament.id } },
          update: {},
          create: { playerId: player.id, tournamentId: tournament.id },
        });
      }
    }

    console.log(`    ✓ ${p.name}`);
  }

  console.log(`\n✅ Seed complete!`);
  console.log(`   Leagues:     ${LEAGUES.length}`);
  console.log(`   Clubs:       ${CLUBS.length}`);
  console.log(`   Tournaments: ${TOURNAMENTS.length}`);
  console.log(`   Managers:    ${MANAGERS.length}`);
  console.log(`   Players:     ${PLAYERS.length}`);
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
